import { FYPStage } from '@prisma/client';

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const VALID_STAGE_TRANSITIONS: Record<FYPStage, FYPStage[]> = {
  IDEA_PENDING: [FYPStage.IDEA_APPROVED, FYPStage.IDEA_REJECTED],
  IDEA_APPROVED: [FYPStage.SUPERVISOR_PENDING],
  IDEA_REJECTED: [],
  SUPERVISOR_PENDING: [FYPStage.SUPERVISOR_ASSIGNED],
  SUPERVISOR_ASSIGNED: [FYPStage.PROPOSAL_PENDING],
  PROPOSAL_PENDING: [FYPStage.PROPOSAL_APPROVED, FYPStage.PROPOSAL_REJECTED],
  PROPOSAL_APPROVED: [FYPStage.SRS_PENDING],
  PROPOSAL_REJECTED: [],
  SRS_PENDING: [FYPStage.SRS_APPROVED, FYPStage.SRS_REJECTED],
  SRS_APPROVED: [FYPStage.INTERNAL_PENDING],
  SRS_REJECTED: [],
  INTERNAL_PENDING: [FYPStage.INTERNAL_DONE],
  INTERNAL_DONE: [FYPStage.EXTERNAL_PENDING],
  EXTERNAL_PENDING: [FYPStage.EXTERNAL_DONE],
  EXTERNAL_DONE: [FYPStage.COMPLETED],
  COMPLETED: [],
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
} as const;

export const EVALUATION = {
  MIN_MARKS: 0,
  MAX_MARKS: 100,
} as const;

export const PLAGIARISM = {
  THRESHOLD: 20.0, // 20% similarity threshold
} as const;

